# Generated by Django 2.0.7 on 2019-09-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Get',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100, verbose_name='资料名称')),
                ('count', models.CharField(max_length=10, verbose_name='数量')),
                ('price', models.CharField(max_length=10, verbose_name='价格')),
                ('person', models.CharField(max_length=10, verbose_name='收货人')),
                ('number', models.CharField(max_length=20, verbose_name='手机号码')),
                ('address', models.TextField(verbose_name='收货地址')),
                ('shipments', models.CharField(blank=True, choices=[('0', '待发货'), ('1', '发货')], default=0, max_length=10, verbose_name='发货状态')),
            ],
            options={
                'verbose_name': '资料领取',
                'verbose_name_plural': '资料领取',
            },
        ),
        migrations.CreateModel(
            name='Industrycommittee',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('headImg', models.ImageField(upload_to='head_img', verbose_name='用户头像')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('number', models.CharField(max_length=20, verbose_name='手机号码')),
                ('plotName', models.CharField(max_length=20, verbose_name='业委会名称')),
                ('submitDate', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
                ('check', models.CharField(blank=True, choices=[('0', '待审核'), ('1', '通过'), ('2', '拒绝')], default=0, max_length=10, verbose_name='审核状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '业委会认证',
                'verbose_name_plural': '业委会认证',
            },
        ),
    ]
