# Generated by Django 2.0.7 on 2019-09-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrycommittee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Get',
            new_name='Getdata',
        ),
    ]
