# Generated by Django 2.0.7 on 2019-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrycommittee', '0002_auto_20190905_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdata',
            name='count',
            field=models.IntegerField(verbose_name='数量'),
        ),
    ]
